### ISSUE TITLE
helpers.php 

### ISSUE THREAD

**Issue by elnurxf** [laravelista/Ekko#16]
Hi. There is a bug on file: helpers.php line 53:

Replace: 
`return app(Ekko::class)->areActiveRoutes($string, $output);`
with
`return app(Ekko::class)->areActiveRoutes($routeNames, $output);`

**Comment by mabasic** [comment]
Thank you for letting me know. I have fixed it in version `1.3.1`

**Comment by elnurxf** [comment]
@mabasic welcome!
