### ISSUE TITLE
Support URL wildcards

### ISSUE THREAD

**Issue by danmichaelo** [laravelista/Ekko#19]
Would be useful to be able to do `isActiveURL('/events/*')`. The `isActiveMatch` method is too limiting, since you might not want to match e.g. `users/1/events/123`.

I could prepare a PR for this, but before I do so I'd like to know if it's likely that it would be accepted?

**Comment by mabasic** [comment]
I'm not quite sure about this one. I agree that `isActiveMatch` has its flaws, but if you use `isActiveRoute` or `areActiveRoutes` with wildcards then it solves the problem. 

Currently I will stick to having wildcards only on named routes methods. Maybe in the future I will consider having implementing them in URL methods.
