### ISSUE TITLE
Support route actions

### ISSUE THREAD

**Issue by danmichaelo** [laravelista/Ekko#20]
Laravel provides route lookup by URL, name or action, but only the two first are currently supported by Ekko. Would be useful if Ekko could also support action based route matching:

* Matching a single route action: `isActiveAction('controllerName@action')`
* With wildcard: `isActiveAction('controllerName@*')`

**Comment by mabasic** [comment]
It is that way by choice. I personally find looking up routes by action to be not a great idea and very confusing. That is why I haven't added that functionality to Ekko.
