### ISSUE TITLE
Support for query param strings?

### ISSUE THREAD

**Issue by joshuamabina** [laravelista/Ekko#24]
How can I accomplish the scenario below?

```php
<li class="{{ isActiveURL('/posts?type=featured') }}">
...
</li>
```

**Comment by mabasic** [comment]
Currently, there is no way to do this because Ekko uses `current()` to get the current URL. For this to work it should use `full()`. Maybe in the future, I will change it to be `full` instead of `current`. I am sure that there was a reason behind this decision, but I cannot remember what now.

**Comment by joshuamabina** [comment]
- Could you suggest a quick (and dirty) hack to accomplish this using Ekko?
- Will you be willing to accept a `full()` pull request?

**Comment by mabasic** [comment]
A quick hack without using Ekko:

```
<li class="@if(URL::full() == URL::to('/posts?type=featured') active @endif">...</li>
```

I haven't tested this, but something like this should work.

I am willing to accept a PR for this switch if you add a test for this scenario and update the readme file accordingly.
