### ISSUE TITLE
Support URLs params ?

### ISSUE THREAD

**Issue by karnash** [laravelista/Ekko#6]
hi if i have  my URL

`admin/client/1`

the 1 is a dynamic param.
how i can check that url. ? 
thk a lot

**Comment by mabasic** [comment]
Hello,

it depends on upon how you defined your route. If you used route name like `admin.client` then you could use [`isActiveRoute`](https://github.com/laravelista/Ekko#isactiverouteroutename-output--active)

```
<a href="{{ route('admin.client', $id ) }}" class="{{ Ekko::isActiveRoute('admin.client') }}">
    Client {{ $id }}
</a>
```

Or if you did not define a route name and are using normal URL, you can use:

```
<a href="{{ url('admin/client/' . $id ) }}" class="{{ Ekko::isActiveMatch('admin/client/') }}">
    Client {{ $id }}
</a>
```

I suggest using route names.
